title: From Appalachia to Chicago - A Story of Migration Through the Lens of Family Archives # You will insert your title here.
email: cmill101@illinois.edu, lmart219@illinois.edu
description: by Caden J. Miller and Lesly Martinez # Author names go here.

baseurl: "/TennesseeChicago" # the subpath of your site. Change it if the name of your repository is other than "mindoc"

twitter_username: jekyllrb
github_username:  jekyll

# Build settings

plugins:
  - jekyll-feed

collections:
  mindoc_media:
    output: true
    layout: 'image_description'
